dist: trusty

language: node_js

node_js:
  - "7.10.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq

install:
  - yarn install
  - rm -rf contracts/zeppelin # remove any remaining artifacts from a previous build
  - nohup yarn run testrpc &
  - truffle version

script:
  - yarn run test
  - yarn run lint
notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
