sudo: required

dist: trusty

language: node_js

node_js:
  - "7.10.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq

install:
  - yarn install
  - rm -r contracts/zeppelin
  - yarn run testrpc
  - truffle version

notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
