site_name: DAOstack Arc Docs
site_url: https://daostack.github.io/arc
repo_url: https://github.com/daostack/arc/
repo_name: daostack/arc
site_description: A platform for building DAOs
docs_dir: docs
markdown_extensions:
- admonition
- codehilite:
    linenums: true
- toc:
    permalink: true
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'amber'
extra:
  social:
  - type: 'github'
    link: 'https://github.com/daostack/arc'
  - type: 'slack'
    link: 'https://daostack.slack.com'
  - type: 'telegram'
    link: 'https://t.me/daostackcommunity'
